[package]
name = "recast-cli"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
anyhow.workspace = true
clap.workspace = true
recast-core = { path = "../converter-core" }
recast-engines = { path = "../converter-engines" }
recast-models = { path = "../converter-models" }
serde_json.workspace = true
shell-integration = { path = "../shell-integration" }
